config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('course.urls',namespace='course'))
]

course/urls.py
from django.urls import path
from .views import Indeview,CreateCourse,UpdateView,DeleteView,StudentView,InstratorView
app_name='course'

urlpatterns = [
    path('',Indeview,name='index'),
    path('create/',CreateCourse,name='add'),
    path('update/<int:pk>/',UpdateView,name='update'),
    path('delete/<int:pk>/',DeleteView,name='delete'),
    path('student/',StudentView,name='student'),
    path('instractor/',InstratorView,name='instractor')
]

course/models.py
from django.db import models

# Create your models here.


class Course(models.Model):
    course_id=models.AutoField(primary_key=True)
    course_title=models.CharField(max_length=100)
    instractor_name=models.CharField(max_length=100)
    capacity=models.IntegerField(default=30)
    open_seats=models.IntegerField(default=30)
    
    class Meta:
        verbose_name_plural='Course'
        db_table='course'
    def __str__(self):
        return self.course_title
    
class Students(models.Model):
        reg_no=models.AutoField(primary_key=True)
        name=models.CharField(max_length=100)
        email=models.EmailField(max_length=100)
        course_id=models.ForeignKey('Course',on_delete=models.CASCADE)
        phone=models.CharField(max_length=100)
        instractor_name=models.CharField(max_length=100)
        
        class Meta:
            verbose_name_plural='Students'
            db_table='students'
        def __str__(self):
            return self.name
        
class Instractor(models.Model):
    instractor_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=100)
    email=models.EmailField(max_length=100)
    course_id=models.ForeignKey('Course',on_delete=models.CASCADE)
    phone=models.CharField(max_length=100)
    course_title=models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural='Instractor'
        db_table='instractor'
        
    def __str__(self):
        return self.name
    
    

course/forms.py
from django import forms
from .models import Course


class CourseForm(forms.ModelForm):
    class Meta:
        model=Course
        fields='__all__'
       

course/views.py
from django.shortcuts import render,redirect
from .models import Course,Students,Instractor
from .forms import CourseForm
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
# Create your views here.


def Indeview(request):
    courses=Course.objects.all()
    context={
        'courses':courses
    }
    return render(request,'index.html',context)
#crud
#CreateView

def CreateCourse(request):
    form=CourseForm()
    if request.method=='POST':
        form=CourseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('course:index')
    context={
        'form':form
    }
    return render(request,'create.html',context)
#UpdateView

def UpdateView(request, pk):
    course = get_object_or_404(Course, pk=pk)

    if request.method == 'POST':
        # Update the object with the new data from the form
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            return redirect('course:index')
    else:
        # Show the form for editing the object
        form = CourseForm(instance=course)
        context={
            'form': form
        }

    return render(request, 'update.html',context)


#DELETEView


def DeleteView(request, pk):
    course = get_object_or_404(Course, pk=pk)

    if request.method == 'POST':
        course.delete()
        return redirect('course:index')
    context={
    'course':course
    }

    return render(request, 'delete.html',context)

def StudentView(request):
    students=Students.objects.all()
    context={
        'students':students
    }
    return render(request,'student.html',context)

def InstratorView(request):
    instractors=Instractor.objects.all()
    context={
        'instractors':instractors
    }
    return render(request,'instractor.html',context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Course Management</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'course:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%  url 'course:student' %}">Students</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'course:instractor' %}">Instractors</a>
            </li>
        
          </ul>
        </div>
      </nav>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/create.html
{% extends "base.html" %}
<style>
    .container {
        padding: 2rem 0rem;
      }
      
      h4 {
        margin: 2rem 0rem 1rem;
      }
      
      .table-image {
        td, th {
          vertical-align: middle;
        }
      }
      }
</style>
{% block content %}
<div class="container">
    <div class="row">
      <div class="col-12">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Course ID</th>
              <th scope="col">Course Title</th>
              <th scope="col">Instractor Name</th>
              <th scope="col">Capacity</th>
             
            </tr>
          </thead>
          <tbody>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Add Course</button>
            </form>
          </tbody>
        </table>
        
      </div>
    </div>
  </div>

{% endblock %}

templates/delete.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <h4>Are You sure you want to delete {{course.course_title}}</h4>
          <tbody>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Delete</button>
            </form>
          </tbody>
        </table>
         
      </div>
    </div>
  </div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
<style>
    .container {
        padding: 2rem 0rem;
      }
      
      h4 {
        margin: 2rem 0rem 1rem;
      }
      
      .table-image {
        td, th {
          vertical-align: middle;
        }
      }
      }
</style>
{% block content %}

<div class="container">
    <div class="row">
      <div class="col-12">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Course ID</th>
              <th scope="col">Course Title</th>
              <th scope="col">Instractor Name</th>
              <th scope="col">Capacity</th>
             
            </tr>
          </thead>
          <tbody>
            {% for course in courses %}
            <tr>
              <th scope="row">{{ course.course_id }}</th>
              <td>{{course.course_title}}</td>
              <td>{{course.instractor_name}}</td>
              <td>{{course.capacity}}</td>
              <td><a href="{% url 'course:update' course.pk %}"><button type="button" class="btn btn-success"><i class="far fa-trash-alt"></i>Upadate Course</button></a> </td>
              <td><a href="{% url 'course:delete' course.pk %}"><button type="button" class="btn btn-danger"><i class="far fa-trash-alt"></i>Delete Course</button></a> </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <td>
              <a href="{% url 'course:add' %}"><button type="button" class="btn btn-primary"><i class="far fa-eye">Add Course</i></button></a>
              
              </td>
      </div>
    </div>
  </div>

{% endblock %}

templates/instractor.html
{% extends "base.html" %}
<style>
    .container {
        padding: 2rem 0rem;
      }
      
      h4 {
        margin: 2rem 0rem 1rem;
      }
      
      .table-image {
        td, th {
          vertical-align: middle;
        }
      }
      }
</style>
{% block content %}

<div class="container">
    <div class="row">
      <div class="col-12">
        <h2>Instractors</h2>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">instractor_id</th>
              <th scope="col">Name</th>
              <th scope="col">Email</th>
              <th scope="col">course_id</th>
            
             
             
            </tr>
          </thead>
          <tbody>
            {% for int in instractors %}
            <tr>
              <th scope="row">{{ int.instractor_id }}</th>
              <td>{{int.name}}</td>
              <td>{{int.email}}</td>
              <td>{{int.phone}}</td>
                <td>{{int.course_id}}</td>
             
            </tr>
            {% endfor %}
          </tbody>
        </table>

      </div>
    </div>
  </div>

{% endblock %}

templates/student.html
{% extends "base.html" %}
<style>
    .container {
        padding: 2rem 0rem;
      }
      
      h4 {
        margin: 2rem 0rem 1rem;
      }
      
      .table-image {
        td, th {
          vertical-align: middle;
        }
      }
      }
</style>
{% block content %}

<div class="container">
    <div class="row">
      <div class="col-12">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Reg No</th>
              <th scope="col">Name</th>
              <th scope="col">Email</th>
              <th scope="col">Phone</th>
             
             
            </tr>
          </thead>
          <tbody>
            {% for student in students %}
            <tr>
              <th scope="row">{{ student.reg_no }}</th>
              <td>{{student.name}}</td>
              <td>{{student.email}}</td>
              <td>{{student.phone}}</td>
             
            </tr>
            {% endfor %}
          </tbody>
        </table>

      </div>
    </div>
  </div>

{% endblock %}

templates/update.html
{% extends "base.html" %}
<style>
    .container {
        padding: 2rem 0rem;
      }
      
      h4 {
        margin: 2rem 0rem 1rem;
      }
      
      .table-image {
        td, th {
          vertical-align: middle;
        }
      }
      }
</style>
{% block content %}
<div class="container">
    <div class="row">
      <div class="col-12">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Course ID</th>
              <th scope="col">Course Title</th>
              <th scope="col">Instractor Name</th>
              <th scope="col">Capacity</th>
             
            </tr>
          </thead>
          <tbody>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Updated</button>
            </form>
          </tbody>
        </table>
        
      </div>
    </div>
  </div>

{% endblock %}